import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  DecryptionError,
  changePassword,
  computeFingerprint,
  createVault,
  decryptItem,
  deriveMasterKey,
  deriveSubkeys,
  encryptItem,
  fingerprintRings,
  fromBase64Url,
  fromHex,
  hkdf,
  open,
  seal,
  toBase64Url,
  toHex,
  unlockVault,
  utf8,
  type KdfParams,
} from '../src';

interface Pbkdf2Vector {
  source: string;
  password: string;
  salt: string;
  iterations: number;
  length: number;
  hex: string;
}
interface HkdfVector {
  source: string;
  ikm: string;
  salt: string;
  info: string;
  length: number;
  hex: string;
}
interface GcmVector {
  source: string;
  key: string;
  iv: string;
  plaintext: string;
  ciphertext_and_tag: string;
}
interface Vectors {
  published: { pbkdf2_sha256: Pbkdf2Vector[]; hkdf_sha256: HkdfVector[]; aes_256_gcm: GcmVector[] };
  pvf1: {
    password: string;
    kdf: KdfParams;
    masterKey: string;
    authKey: string;
    wrapKey: string;
    vaultKey: string;
    wrapIv: string;
    wrappedVaultKey: string;
    fingerprint: { bytes: string; code: string; rings: string };
    item: { id: string; json: string; iv: string; envelope: string };
  };
  nfkc: { composed: string; decomposed: string; kdf: KdfParams; masterKey: string };
}

const vectors = JSON.parse(
  readFileSync(fileURLToPath(new URL('../../../spec/vectors/pvf1.json', import.meta.url)), 'utf8'),
) as Vectors;
const v = vectors.pvf1;
const FAST = 1000; // iterations for tests that don't check exact outputs

describe('published vectors', () => {
  it.each(vectors.published.pbkdf2_sha256)(
    'PBKDF2-SHA256: $source, $iterations iterations',
    async (t) => {
      const base = await crypto.subtle.importKey('raw', utf8(t.password), 'PBKDF2', false, [
        'deriveBits',
      ]);
      const bits = await crypto.subtle.deriveBits(
        { name: 'PBKDF2', hash: 'SHA-256', salt: utf8(t.salt), iterations: t.iterations },
        base,
        t.length * 8,
      );
      expect(toHex(new Uint8Array(bits))).toBe(t.hex);
    },
  );

  it('HKDF-SHA256: RFC 5869 A.1', async () => {
    const t = vectors.published.hkdf_sha256[0] as HkdfVector;
    const base = await crypto.subtle.importKey('raw', fromHex(t.ikm), 'HKDF', false, [
      'deriveBits',
    ]);
    const bits = await crypto.subtle.deriveBits(
      { name: 'HKDF', hash: 'SHA-256', salt: fromHex(t.salt), info: fromHex(t.info) },
      base,
      t.length * 8,
    );
    expect(toHex(new Uint8Array(bits))).toBe(t.hex);
  });

  it.each(vectors.published.aes_256_gcm)('AES-256-GCM: $source', async (t) => {
    const key = await crypto.subtle.importKey('raw', fromHex(t.key), 'AES-GCM', false, ['encrypt']);
    const ct = await crypto.subtle.encrypt(
      { name: 'AES-GCM', iv: fromHex(t.iv) },
      key,
      fromHex(t.plaintext),
    );
    expect(toHex(new Uint8Array(ct))).toBe(t.ciphertext_and_tag);
  });
});

describe('pvf1 vectors (generated by an independent implementation)', () => {
  it('derives the master key, auth key and wrap key', async () => {
    const masterKey = await deriveMasterKey(v.password, v.kdf);
    expect(toBase64Url(masterKey)).toBe(v.masterKey);
    const { authKey, wrapKey } = await deriveSubkeys(masterKey);
    expect(toBase64Url(authKey)).toBe(v.authKey);
    expect(toBase64Url(wrapKey)).toBe(v.wrapKey);
  });

  it('wraps the vault key and computes the fingerprint', async () => {
    const vault = await createVault(v.password, {
      kdf: v.kdf,
      vaultKeyBytes: fromBase64Url(v.vaultKey),
      wrapIv: fromBase64Url(v.wrapIv),
    });
    expect(vault.header.wrappedVaultKey).toBe(v.wrappedVaultKey);
    expect(vault.header.fingerprint).toBe(v.fingerprint.code);
    expect(toBase64Url(vault.fingerprint.bytes)).toBe(v.fingerprint.bytes);
    expect(toBase64Url(vault.fingerprint.rings)).toBe(v.fingerprint.rings);
    expect(toBase64Url(await fingerprintRings(v.fingerprint.code))).toBe(v.fingerprint.rings);
    expect(toBase64Url(vault.authKey)).toBe(v.authKey);
  });

  it('encrypts an item to the exact expected envelope', async () => {
    const vault = await unlockVault(v.password, {
      format: 'pvf1',
      kdf: v.kdf,
      wrappedVaultKey: v.wrappedVaultKey,
      fingerprint: v.fingerprint.code,
    });
    const envelope = await encryptItem(
      vault.vaultKey,
      v.item.id,
      JSON.parse(v.item.json),
      fromBase64Url(v.item.iv),
    );
    expect(envelope).toBe(v.item.envelope);
    expect(await decryptItem(vault.vaultKey, v.item.id, v.item.envelope)).toEqual(
      JSON.parse(v.item.json),
    );
  });

  it('normalizes passwords with NFKC', async () => {
    const { composed, decomposed, kdf, masterKey } = vectors.nfkc;
    expect(composed).not.toBe(decomposed);
    expect(toBase64Url(await deriveMasterKey(composed, kdf))).toBe(masterKey);
    expect(toBase64Url(await deriveMasterKey(decomposed, kdf))).toBe(masterKey);
  });
});

describe('vault behaviour', () => {
  it('round-trips create, lock and unlock', async () => {
    const created = await createVault('hunter2 is not enough', { iterations: FAST });
    const envelope = await encryptItem(created.vaultKey, 'item-1', { title: 'GitHub' });
    const unlocked = await unlockVault('hunter2 is not enough', created.header);
    expect(await decryptItem(unlocked.vaultKey, 'item-1', envelope)).toEqual({ title: 'GitHub' });
    expect(unlocked.authKey).toEqual(created.authKey);
  });

  it('rejects a wrong master password', async () => {
    const { header } = await createVault('right password', { iterations: FAST });
    await expect(unlockVault('wrong password', header)).rejects.toBeInstanceOf(DecryptionError);
  });

  it('rejects a header whose fingerprint was swapped', async () => {
    const { header } = await createVault('right password', { iterations: FAST });
    await expect(
      unlockVault('right password', { ...header, fingerprint: '0000 0000 0000' }),
    ).rejects.toThrow('fingerprint');
  });

  it('refuses ciphertext moved to a different item ID', async () => {
    const { vaultKey } = await createVault('pw', { iterations: FAST });
    const envelope = await encryptItem(vaultKey, 'item-a', { secret: 1 });
    await expect(decryptItem(vaultKey, 'item-b', envelope)).rejects.toBeInstanceOf(DecryptionError);
  });

  it('detects tampered ciphertext', async () => {
    const key = crypto.getRandomValues(new Uint8Array(32));
    const envelope = await seal(key, utf8('top secret'), 'aad');
    const [prefix, iv, ct] = envelope.split('.') as [string, string, string];
    const bytes = fromBase64Url(ct);
    bytes[0] = (bytes[0] as number) ^ 1;
    await expect(open(key, `${prefix}.${iv}.${toBase64Url(bytes)}`, 'aad')).rejects.toBeInstanceOf(
      DecryptionError,
    );
  });

  it('rejects malformed envelopes', async () => {
    const key = crypto.getRandomValues(new Uint8Array(32));
    for (const bad of ['', 'pvf1', 'pvf2.AAAA.AAAA', 'pvf1.AAAA.AAAA', 'pvf1.!!!.AAAA']) {
      await expect(open(key, bad, 'aad')).rejects.toBeInstanceOf(DecryptionError);
    }
  });

  it('uses a fresh IV every time', async () => {
    const key = crypto.getRandomValues(new Uint8Array(32));
    const a = await seal(key, utf8('same'), 'aad');
    const b = await seal(key, utf8('same'), 'aad');
    expect(a).not.toBe(b);
  });

  it('changes the master password without re-encrypting items', async () => {
    const created = await createVault('old password', { iterations: FAST });
    const envelope = await encryptItem(created.vaultKey, 'item-1', { title: 'Bank' });
    const changed = await changePassword('old password', 'new password', created.header);
    expect(changed.header.fingerprint).toBe(created.header.fingerprint);
    await expect(unlockVault('old password', changed.header)).rejects.toBeInstanceOf(
      DecryptionError,
    );
    const unlocked = await unlockVault('new password', changed.header);
    expect(await decryptItem(unlocked.vaultKey, 'item-1', envelope)).toEqual({ title: 'Bank' });
  });

  it('keeps the vault key non-extractable', async () => {
    const { vaultKey } = await createVault('pw', { iterations: FAST });
    expect(vaultKey.extractable).toBe(false);
    await expect(crypto.subtle.exportKey('raw', vaultKey)).rejects.toThrow();
  });

  it('derives different fingerprints for different vault keys', async () => {
    const a = await computeFingerprint(crypto.getRandomValues(new Uint8Array(32)));
    const b = await computeFingerprint(crypto.getRandomValues(new Uint8Array(32)));
    expect(a.code).toMatch(/^[0-9A-F]{4} [0-9A-F]{4} [0-9A-F]{4}$/);
    expect(a.code).not.toBe(b.code);
  });

  it('rejects unsupported KDFs', async () => {
    const kdf = { alg: 'md5', iterations: 1, salt: '' } as unknown as KdfParams;
    await expect(deriveMasterKey('pw', kdf)).rejects.toThrow('Unsupported KDF');
  });

  it('exposes HKDF with distinct outputs per info string', async () => {
    const ikm = new Uint8Array(32);
    expect(toHex(await hkdf(ikm, 'a', 32))).not.toBe(toHex(await hkdf(ikm, 'b', 32)));
  });
});
