#!/usr/bin/env python3
"""Generate spec/vectors/pvf1.json from an implementation independent of ours.

Uses the `cryptography` package (OpenSSL underneath) for PBKDF2, HKDF and
AES-GCM. Before writing anything it checks published test vectors (RFC 7914,
RFC 5869, NIST GCM), so the output can be trusted as a reference.

Run from the repo root:  python3 spec/vectors/generate.py
"""
import base64
import hashlib
import json
import pathlib
import unicodedata

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

OUT = pathlib.Path(__file__).with_name("pvf1.json")


def b64u(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def pbkdf2(password: bytes, salt: bytes, iterations: int, length: int) -> bytes:
    return PBKDF2HMAC(hashes.SHA256(), length, salt, iterations).derive(password)


def hkdf(ikm: bytes, info: bytes, length: int, salt: bytes | None = None) -> bytes:
    return HKDF(hashes.SHA256(), length, salt, info).derive(ikm)


def seal(key: bytes, iv: bytes, plaintext: bytes, aad: bytes) -> str:
    ct = AESGCM(key).encrypt(iv, plaintext, aad)
    return f"pvf1.{b64u(iv)}.{b64u(ct)}"


def master_key(password: str, salt: bytes, iterations: int) -> bytes:
    return pbkdf2(unicodedata.normalize("NFKC", password).encode(), salt, iterations, 32)


# --- Published vectors: prove the reference implementation is correct -------

# RFC 7914 section 11, PBKDF2-HMAC-SHA256
assert pbkdf2(b"passwd", b"salt", 1, 64).hex() == (
    "55ac046e56e3089fec1691c22544b605f94185216dde0465e68b9d57c20dacbc"
    "49ca9cccf179b645991664b39d77ef317c71b845b1e30bd509112041d3a19783"
)
assert pbkdf2(b"Password", b"NaCl", 80000, 64).hex() == (
    "4ddcd8f60b98be21830cee5ef22701f9641a4418d04c0414aeff08876b34ab56"
    "a1d425a1225833549adb841b51c9b3176a272bdebba1d078478f62b397f33c8d"
)

# RFC 5869 appendix A.1, HKDF-SHA256 test case 1
assert hkdf(bytes([0x0B] * 22), bytes(range(0xF0, 0xFA)), 42, bytes(range(0x0D))).hex() == (
    "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865"
)

# NIST GCM specification, test cases 13 and 14 (AES-256, zero key and IV)
assert AESGCM(bytes(32)).encrypt(bytes(12), b"", None).hex() == "530f8afbc74536b9a963b4f1c4cb738b"
assert AESGCM(bytes(32)).encrypt(bytes(12), bytes(16), None).hex() == (
    "cea7403d4d606b6e074ec5d3baf39d18" "d0d1c8a799996bf0265b98b5d48ab919"
)

# --- PassVaultify pvf1 vectors -----------------------------------------------

password = "correct horse battery staple"
salt = bytes(range(16))
iterations = 600_000
mk = master_key(password, salt, iterations)
auth_key = hkdf(mk, b"passvaultify/v1/auth", 32)
wrap_key = hkdf(mk, b"passvaultify/v1/wrap", 32)

vault_key = bytes(range(0x20, 0x40))
wrap_iv = bytes(range(0xA0, 0xAC))
wrapped_vault_key = seal(wrap_key, wrap_iv, vault_key, b"passvaultify/v1/vault-key")

fp = hkdf(vault_key, b"passvaultify/v1/fingerprint", 16)
fp_hex = fp[:6].hex().upper()
fingerprint_code = " ".join(fp_hex[i : i + 4] for i in range(0, 12, 4))
rings = hashlib.sha256(f"passvaultify/v1/rings/{fingerprint_code}".encode()).digest()[:16]

item_id = "3f2b8c1e-9d4a-4f6b-8e2c-1a5d7f9b0c3e"
item_json = json.dumps(
    {
        "type": "login",
        "title": "GitHub",
        "username": "furmak331",
        "password": "k7#Tq-v9Rm!2xLp",
        "urls": ["https://github.com"],
    },
    separators=(",", ":"),
)
item_iv = bytes(range(0xB0, 0xBC))
item_envelope = seal(vault_key, item_iv, item_json.encode(), f"passvaultify/v1/item/{item_id}".encode())

# NFKC: composed and decomposed forms of the same password derive the same key
nfkc_salt = bytes(16)
composed = "påsswörd"
decomposed = "påsswörd"
assert composed != decomposed
nfkc_key = master_key(composed, nfkc_salt, 1000)
assert nfkc_key == master_key(decomposed, nfkc_salt, 1000)

vectors = {
    "description": "PassVaultify pvf1 test vectors. Generated by spec/vectors/generate.py; do not edit by hand.",
    "published": {
        "pbkdf2_sha256": [
            {"source": "RFC 7914 s11", "password": "passwd", "salt": "salt", "iterations": 1, "length": 64,
             "hex": pbkdf2(b"passwd", b"salt", 1, 64).hex()},
            {"source": "RFC 7914 s11", "password": "Password", "salt": "NaCl", "iterations": 80000, "length": 64,
             "hex": pbkdf2(b"Password", b"NaCl", 80000, 64).hex()},
        ],
        "hkdf_sha256": [
            {"source": "RFC 5869 A.1", "ikm": "0b" * 22, "salt": bytes(range(0x0D)).hex(),
             "info": bytes(range(0xF0, 0xFA)).hex(), "length": 42,
             "hex": hkdf(bytes([0x0B] * 22), bytes(range(0xF0, 0xFA)), 42, bytes(range(0x0D))).hex()},
        ],
        "aes_256_gcm": [
            {"source": "NIST GCM test case 13", "key": "00" * 32, "iv": "00" * 12, "plaintext": "",
             "ciphertext_and_tag": "530f8afbc74536b9a963b4f1c4cb738b"},
            {"source": "NIST GCM test case 14", "key": "00" * 32, "iv": "00" * 12, "plaintext": "00" * 16,
             "ciphertext_and_tag": "cea7403d4d606b6e074ec5d3baf39d18d0d1c8a799996bf0265b98b5d48ab919"},
        ],
    },
    "pvf1": {
        "password": password,
        "kdf": {"alg": "pbkdf2-sha256", "iterations": iterations, "salt": b64u(salt)},
        "masterKey": b64u(mk),
        "authKey": b64u(auth_key),
        "wrapKey": b64u(wrap_key),
        "vaultKey": b64u(vault_key),
        "wrapIv": b64u(wrap_iv),
        "wrappedVaultKey": wrapped_vault_key,
        "fingerprint": {"bytes": b64u(fp), "code": fingerprint_code, "rings": b64u(rings)},
        "item": {"id": item_id, "json": item_json, "iv": b64u(item_iv), "envelope": item_envelope},
    },
    "nfkc": {
        "composed": composed,
        "decomposed": decomposed,
        "kdf": {"alg": "pbkdf2-sha256", "iterations": 1000, "salt": b64u(nfkc_salt)},
        "masterKey": b64u(nfkc_key),
    },
}

OUT.write_text(json.dumps(vectors, indent=2, ensure_ascii=False) + "\n")
print(f"published vectors verified; wrote {OUT}")
