spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/passvaultify}
spring.datasource.username=${DATABASE_USER:passvaultify}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.hikari.maximum-pool-size=${DATABASE_POOL_SIZE:10}
