/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness check */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Server version and fingerprint
     * @description Clients show the fingerprint on first connect so the user can compare it with the server's admin page, then pin it.
     */
    get: operations['getServerInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/prelogin': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get KDF settings for an email
     * @description Returns the KDF settings the client needs to derive the auth key.
     *     For unknown emails the server returns consistent, plausible fake
     *     settings derived from the email, so accounts can't be enumerated.
     */
    post: operations['prelogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an account
     * @description Uploads a vault created on the client. Only the auth key is sent; the server stores Argon2id(authKey).
     */
    post: operations['createAccount'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/accounts/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete the account
     * @description Removes the account, its devices and every item. Needs the auth key, so a stolen session token alone can't do it.
     */
    delete: operations['deleteAccount'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign in with the auth key */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate the refresh token
     * @description Each refresh token works once. Reusing an old one revokes the whole session.
     */
    post: operations['refreshTokens'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** End this device's session */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/vault/header': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Store a new header after a master password change
     * @description The vault key is re-wrapped on the client. Items are not re-encrypted. The fingerprint must not change, since it's the same vault key.
     */
    put: operations['updateVaultHeader'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/sync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Items changed since a revision */
    get: operations['getChanges'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/items/{itemId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Create, update or delete an item
     * @description Optimistic concurrency: send the revision you last saw. If the server
     *     has a newer one it returns 409 with its copy, and the client keeps
     *     both versions and asks the user.
     */
    put: operations['putItem'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Change notifications (Server-Sent Events)
     * @description Events carry no item data:
     *
     *     - `vault-changed`, data `{"revision": n}`: sent on connect with the
     *       current revision, then after every write. Sync from your last revision.
     *     - `session-ended`: this device was signed out (remotely, by a password
     *       change, or by refresh-token reuse). Lock and sign in again.
     *
     *     A comment line is sent every 25 seconds to keep proxies from closing
     *     the stream. Browsers' EventSource can't send an Authorization header,
     *     so clients read the stream with fetch.
     */
    get: operations['streamEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/devices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Signed-in devices */
    get: operations['listDevices'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/devices/{deviceId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Sign a device out remotely */
    delete: operations['signOutDevice'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Binary data, base64url without padding. */
    Base64Url: string;
    /** @description AES-256-GCM ciphertext in the pvf1 envelope format. */
    Envelope: string;
    KdfParams: {
      /** @enum {string} */
      alg: 'pbkdf2-sha256';
      iterations: number;
      salt: components['schemas']['Base64Url'];
    };
    VaultHeader: {
      /** @constant */
      format: 'pvf1';
      kdf: components['schemas']['KdfParams'];
      wrappedVaultKey: components['schemas']['Envelope'];
      fingerprint: string;
    };
    ItemWrite: {
      /**
       * Format: int64
       * @description 0 when creating a new item.
       */
      expectedRevision: number;
      deleted: boolean;
      data?: components['schemas']['Envelope'];
    };
    ItemRecord: {
      /** Format: uuid */
      id: string;
      /** Format: int64 */
      revision: number;
      /** Format: date-time */
      updatedAt: string;
      /** @description Tombstone. Deleted items keep their ID and revision so other devices learn about the deletion. */
      deleted: boolean;
      data?: components['schemas']['Envelope'];
    };
    Tokens: {
      accessToken: string;
      refreshToken: string;
      /** @description Access token lifetime in seconds. */
      expiresIn: number;
    };
    DeviceInput: {
      name: string;
      /** @enum {string} */
      kind: 'extension' | 'web' | 'cli';
    };
    Device: components['schemas']['DeviceInput'] & {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      lastSeenAt: string;
      /** @description True for the device making this request. */
      current: boolean;
    };
    ServerInfo: {
      version: string;
      fingerprint: string;
      /** @enum {string} */
      registration: 'open' | 'invite-only' | 'closed';
    };
    Problem: {
      /** Format: uri-reference */
      type?: string;
      title: string;
      status: number;
      detail?: string;
    };
  };
  responses: {
    /** @description An error, as RFC 9457 problem details. */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Too many attempts. Retry after the number of seconds in the Retry-After header. */
    RateLimited: {
      headers: {
        'Retry-After'?: number;
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    ItemId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The server is up. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            status: 'ok';
          };
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  getServerInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server identity. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServerInfo'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  prelogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description KDF settings. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            kdf: components['schemas']['KdfParams'];
          };
        };
      };
      400: components['responses']['Problem'];
      429: components['responses']['RateLimited'];
    };
  };
  createAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
          authKey: components['schemas']['Base64Url'];
          header: components['schemas']['VaultHeader'];
        };
      };
    };
    responses: {
      /** @description Account created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            accountId: string;
          };
        };
      };
      400: components['responses']['Problem'];
      /** @description The server isn't accepting new accounts. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      409: components['responses']['Problem'];
      429: components['responses']['RateLimited'];
    };
  };
  deleteAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          authKey: components['schemas']['Base64Url'];
        };
      };
    };
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['Problem'];
      401: components['responses']['Problem'];
      /** @description The auth key is wrong. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
          authKey: components['schemas']['Base64Url'];
          device: components['schemas']['DeviceInput'];
        };
      };
    };
    responses: {
      /** @description Signed in. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            tokens: components['schemas']['Tokens'];
            header: components['schemas']['VaultHeader'];
          };
        };
      };
      400: components['responses']['Problem'];
      401: components['responses']['Problem'];
      429: components['responses']['RateLimited'];
    };
  };
  refreshTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken: string;
        };
      };
    };
    responses: {
      /** @description New tokens. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Tokens'];
        };
      };
      401: components['responses']['Problem'];
      429: components['responses']['RateLimited'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Problem'];
    };
  };
  updateVaultHeader: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentAuthKey: components['schemas']['Base64Url'];
          newAuthKey: components['schemas']['Base64Url'];
          header: components['schemas']['VaultHeader'];
        };
      };
    };
    responses: {
      /** @description Header updated. Other devices must sign in again. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['Problem'];
      401: components['responses']['Problem'];
      /** @description currentAuthKey is wrong. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  getChanges: {
    parameters: {
      query?: {
        /**
         * @description Last vault revision the client has. Omit for a full sync. A value
         *     ahead of the server's revision (the server was restored from an
         *     older backup) gets a full sync, and the lower revision in the
         *     response tells the client to reconcile.
         */
        since?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Changed items, including deletions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * Format: int64
             * @description The vault's current revision. Pass it as `since` next time.
             */
            revision: number;
            items: components['schemas']['ItemRecord'][];
          };
        };
      };
      400: components['responses']['Problem'];
      401: components['responses']['Problem'];
    };
  };
  putItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['ItemId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ItemWrite'];
      };
    };
    responses: {
      /** @description Saved. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemRecord'];
        };
      };
      400: components['responses']['Problem'];
      401: components['responses']['Problem'];
      /** @description The vault has reached its item limit. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description The item changed on another device. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            current: components['schemas']['ItemRecord'];
          };
        };
      };
      /** @description The encrypted item is larger than the server allows. */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  streamEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description An event stream. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      401: components['responses']['Problem'];
    };
  };
  listDevices: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Devices with an active session. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Device'][];
        };
      };
      401: components['responses']['Problem'];
    };
  };
  signOutDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deviceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The device's session was revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['Problem'];
      401: components['responses']['Problem'];
      404: components['responses']['Problem'];
    };
  };
}
